# Generated by Django 5.0.7 on 2024-11-23 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
