# Generated by Django 5.0.7 on 2024-08-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdetails',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='listdetails',
            name='user',
        ),
    ]
