# Generated by Django 5.0.7 on 2024-08-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='category',
            field=models.CharField(choices=[('No category', 'No category'), ('Fashion', 'Fashion'), ('Art & Crafts', 'Art & Crafts'), ('Electronics', 'Electronics'), ('Skincare', 'Skincare'), ('Home & Kitchen', 'Home & Kitchen'), ('Jewelry & Accessories', 'Jewelry & Accessories')], default='No category', max_length=50),
        ),
    ]
