# Generated by Django 5.0.7 on 2024-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListing',
            new_name='CreateListing',
        ),
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_list', models.ManyToManyField(blank=True, related_name='listings', to='auctions.createlisting')),
            ],
        ),
    ]
