# Generated by Django 5.0.7 on 2024-08-10 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listdetails_comment_remove_listdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
