# Generated by Django 5.0.7 on 2024-08-10 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_createlisting_user_alter_createlisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
