# Generated by Django 5.0.7 on 2024-08-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='description',
            field=models.TextField(default='No description', max_length=500),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
