# Generated by Django 5.0.7 on 2024-08-03 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_createlisting_description_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('list_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_details', to='auctions.createlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
