# Generated by Django 5.0.7 on 2024-08-05 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
