# Generated by Django 5.0.7 on 2024-08-10 13:42

import auctions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_createlisting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='user',
            field=models.ForeignKey(default=auctions.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
