# Generated by Django 5.0.7 on 2024-08-05 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_createlisting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Art & Crafts', 'Art & Crafts'), ('Electronics', 'Electronics'), ('Skincare', 'Skincare')], default='No category', max_length=50),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='description',
            field=models.CharField(default='No description', max_length=64),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='image_url',
            field=models.URLField(max_length=50, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
