# Generated by Django 5.0.7 on 2024-08-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_createlisting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='user',
            field=models.ForeignKey(default='Username', on_delete=django.db.models.deletion.CASCADE, related_name='auction_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='createlisting',
            name='user',
            field=models.ForeignKey(default='Username', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
