# Generated by Django 5.0.7 on 2024-08-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlist_user_createlisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='createlisting',
            name='user',
        ),
    ]
