# Generated by Django 5.0.7 on 2024-08-05 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auctionlist_user_remove_createlisting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(validators=[django.core.validators.MinLengthValidator(45)])),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(default='No description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Art & Crafts', 'Art & Crafts'), ('Electronics', 'Electronics'), ('Skincare', 'Skincare')], default='No category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='auction_list',
            field=models.ManyToManyField(blank=True, related_name='lists', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='listdetails',
            name='list_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='auctions.auctionlisting'),
        ),
        migrations.DeleteModel(
            name='CreateListing',
        ),
    ]
