# Generated by Django 5.0.7 on 2024-08-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_comment_list_details_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdetails',
            name='comment',
        ),
    ]
