# Generated by Django 5.0.7 on 2024-08-06 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_createlisting_alter_auctionlist_auction_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.DeleteModel(
            name='AuctionList',
        ),
    ]
