# Generated by Django 5.0.7 on 2024-08-08 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_createlisting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='user',
            field=models.ForeignKey(default='Username', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
