# Generated by Django 5.0.7 on 2024-08-09 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_createlisting_category_createlisting_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
