# Generated by Django 5.0.7 on 2024-08-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_createlisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='user',
        ),
    ]
