# Generated by Django 5.0.7 on 2024-08-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_createlisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdetails',
            name='user',
        ),
    ]
