# Generated by Django 5.0.7 on 2024-08-09 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(40)]),
        ),
    ]
