# Generated by Django 5.0.7 on 2024-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_createlisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
